spring.application.name=medical-service
spring.datasource.url=jdbc:postgresql://ep-red-bird-amc00xop.c-5.us-east-1.aws.neon.tech:5432/medical_records_db?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_7UrWK8EFNaOw
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081
spring.flyway.enabled=false

app.upload.base-dir=uploads
app.upload.prescriptions-folder=prescriptions
app.upload.medical-record-folder=medical-records
app.upload.url-prefix=/medical/uploads


# Auth service integration
app.auth-service.base-url=${AUTH_SERVICE_BASE_URL:http://localhost:8086}

# Internal service auth between auth-service and profile-service
app.internal.api-key=${INTERNAL_API_KEY:profile-internal-dev-key}


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Multipart file upload configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.location=./medical/uploads