spring.application.name=symptom-checker-service

server.port=8080

spring.datasource.url=jdbc:postgresql://ep-red-bird-amc00xop.c-5.us-east-1.aws.neon.tech:5432/symptom_checker_db?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_7UrWK8EFNaOw
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging Configuration
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# JWT Configuration
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

# Serper Configuration
serper.api.key=b81e1075d4e2e241480aa8441d07f9230608b8a2
serper.api.url=https://google.serper.dev/search
