spring.application.name=appointment_service
spring.datasource.url=jdbc:mysql://localhost:3306/appointment_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

server.port=8084
auth.service.base-url=http://localhost:8086
profile.service.base-url=http://localhost:8083
payment.service.base-url=http://localhost:8085
notification.service.base-url=http://localhost:8082
notification.service.sms-path=/api/notifications/message
notification.service.email-path=/api/notifications/email
app.internal.api-key=${INTERNAL_API_KEY:profile-internal-dev-key}
appointments.reminder.scheduler-cron=0 */5 * * * *
