spring.application.name=appointment_service
spring.datasource.url=jdbc:postgresql://ep-red-bird-amc00xop.c-5.us-east-1.aws.neon.tech:5432/appointment_db?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_7UrWK8EFNaOw
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

server.port=8084
auth.service.base-url=http://localhost:8086
profile.service.base-url=http://localhost:8083
payment.service.base-url=http://localhost:8085
notification.service.base-url=http://localhost:8082
notification.service.sms-path=/api/notifications/message
notification.service.email-path=/api/notifications/email
app.internal.api-key=${INTERNAL_API_KEY:profile-internal-dev-key}
appointments.reminder.scheduler-cron=0 */5 * * * *
