version: "4"
services:
  medicalrecord-mysql:
    image: mysql:8.0
    container_name: medicalrecord-mysql
    environment:
      MYSQL_ROOT_PASSWORD: KThanu@2002
      MYSQL_DATABASE: medical_records
    ports:
      - "3308:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pKThanu@2002" ]
      interval: 10s
      timeout: 5s
      retries: 5
  medical-service:
    build: .
    container_name: medical-service
    depends_on:
      medicalrecord-mysql:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://medicalrecord-mysql:3306/medical_records?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: KThanu@2002