version: "4"
services:
  medical-service:
    build: .
    image: medical-service-app
    container_name: medical-service
    ports:
      - "8081:8081"
    environment:
      AUTH_SERVICE_BASE_URL: http://auth-service:8086