apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "KThanu@2002"
            - name: MYSQL_DATABASE
              value: "medical_records"
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: medicalrecord-mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-service
spec:
  selector:
    matchLabels:
      app: medical-service
  template:
    metadata:
      labels:
        app: medical-service
    spec:
      containers:
        - name: medical-service
          image: thanu04/medical-service-app:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://medicalrecord-mysql:3306/medical_records?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "KThanu@2002"
            - name: AUTH_SERVICE_BASE_URL
              value: "http://auth-service:8086"
          resources:
            requests:
              cpu: "250m"
            limits:
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: medical-service
spec:
  selector:
    app: medical-service
  ports:
    - port: 8081
      targetPort: 8081
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: medical-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: medical-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50