# MySQL Deployment for auth-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice-mysql
  template:
    metadata:
      labels:
        app: authservice-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "KThanu@2002"
            - name: MYSQL_DATABASE
              value: "auth_db"
          ports:
            - containerPort: 3306
          args:
            - "--character-set-server=utf8mb4"
            - "--collation-server=utf8mb4_unicode_ci"

---
# MySQL Service for auth-service
apiVersion: v1
kind: Service
metadata:
  name: authservice-mysql
spec:
  selector:
    app: authservice-mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP

---
# Redis Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379

---
# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP

---
# Auth Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: thanu04/auth-service-app:latest
          ports:
            - containerPort: 8086
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://authservice-mysql:3306/auth_db?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "KThanu@2002"
            - name: SPRING_DATA_REDIS_HOST
              value: "redis-service"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"

---
# Auth Service LoadBalancer
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - port: 8086
      targetPort: 8086
  type: LoadBalancer