services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - auth-network

  auth-service:
    build: .
    image: auth-service-app
    container_name: auth-service
    ports:
      - "8086:8086"
    depends_on:
      authservice-mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      PROFILE_SERVICE_BASE_URL: http://profile-service:8083
      NOTIFICATION_SERVICE_BASE_URL: http://notification-service:8082
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge