spring.application.name=payment_service
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=jdbc:mysql://localhost:3306/payment_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8085
auth.service.base-url=http://localhost:8086
appointment.service.base-url=http://localhost:8084
stripe.secret-key=${STRIPE_SECRET_KEY:}
stripe.currency=${STRIPE_CURRENCY:lkr}
payment.default-consultation-fee=${PAYMENT_DEFAULT_CONSULTATION_FEE:500}
payment.default-auto-refund-enabled=${PAYMENT_DEFAULT_AUTO_REFUND_ENABLED:true}
payment.default-refund-percentage=${PAYMENT_DEFAULT_REFUND_PERCENTAGE:100}
