spring.application.name=payment_service
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://ep-red-bird-amc00xop.c-5.us-east-1.aws.neon.tech:5432/payment_db?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_7UrWK8EFNaOw
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


server.port=8085
auth.service.base-url=http://localhost:8086
appointment.service.base-url=http://localhost:8084
stripe.secret-key=${STRIPE_SECRET_KEY:}
stripe.currency=${STRIPE_CURRENCY:lkr}
payment.default-consultation-fee=${PAYMENT_DEFAULT_CONSULTATION_FEE:500}
payment.default-auto-refund-enabled=${PAYMENT_DEFAULT_AUTO_REFUND_ENABLED:true}
payment.default-refund-percentage=${PAYMENT_DEFAULT_REFUND_PERCENTAGE:100}
notification.service.base-url=http://localhost:8082
notification.service.sms-path=/api/notifications/message
app.internal.api-key=${INTERNAL_API_KEY:profile-internal-dev-key}
