services:
  profile-service:
    build: .
    image: profile-service-app
    container_name: profile-service
    ports:
      - "8083:8083"
    environment:
      AUTH_SERVICE_BASE_URL: http://auth-service:8086
    networks:
      - profile-network

networks:
  profile-network:
    driver: bridge